# Generated by Django 5.1.5 on 2025-03-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10)),
                ('curso', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='CadastroProfessor',
        ),
    ]
