# Generated by Django 5.1.5 on 2025-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cadastrodisciplina_rename_cadastro_cadastroprofessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('sala', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=100)),
                ('periodo', models.CharField(choices=[('M', 'MANHÃ'), ('T', 'TARDE'), ('N', 'NOITE'), ('S', 'SABADO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCurso', models.IntegerField()),
                ('curso', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('ha', models.FloatField()),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTurma', models.CharField(max_length=10)),
                ('turma', models.IntegerField()),
            ],
        ),
    ]
